# -*- coding: utf-8 -*-
"""17Dictionary1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v34rjSu6_NelB7NQ1lwwQyMobHb3oTxG

# **Dictionary**

how to make dictionary
"""

dictionary={
    "CustomerName":"yash",
    "product":"phone",
    "model":"samsung galaxy A55",
    "brand":"redme",
    "price":27500

}
print(dictionary)

"""#Add value"""

dictionary["paymentmode"]="UPI"
print(dictionary)

"""#Change value"""

dictionary["brand"]="samsung"
print(dictionary)

"""# filter"""

print(dictionary["CustomerName"])

print(dictionary["brand"])

print(dictionary["model"])

